package GameClient.UI;

import GameClient.GameClient;
import GameClient.GameVariables;
import GameClient.Networking.SocketClient;
import java.io.IOException;
import javax.swing.WindowConstants;

/**
 *
 * @author Kedi Agbogre <kedi97@gmail.com>
 */
public final class GameOverScreen extends javax.swing.JDialog {
    private final GameClient awt;
    /**
     * Creates new form DeadScreen
     * @param awt
     * @param modal
     */
    public GameOverScreen(GameClient awt, boolean modal) {
        super(awt.getContainer(), modal);
        this.awt = awt;
        
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
                
        initComponents();
        
        setTitle(GameVariables.BUNDLE.getString("TANK_KILLED_TITLE"));
        setResizable(false);
        setLocationRelativeTo(awt.getContainer());
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonReappear = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GameClient/Resources/Sprites/TankDemolition.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = GameVariables.BUNDLE; // NOI18N
        jLabel2.setText(bundle.getString("TANK_KILLED_DESCRIPTION")); // NOI18N

        jButtonReappear.setText(bundle.getString("YES")); // NOI18N
        jButtonReappear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReappearActionPerformed(evt);
            }
        });

        jButtonExit.setText(bundle.getString("EXIT")); // NOI18N
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonReappear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReappear)
                    .addComponent(jButtonExit))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReappearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReappearActionPerformed
        dispose();
        awt.close(false);
        
        GameClient gameClient = new GameClient();
        SocketClient socketClient = new SocketClient(gameClient);

        gameClient.setSocketClient(socketClient);
        
        try {
            socketClient.connect(awt.getServerAddress()); 
            gameClient.setServerAddress(awt.getServerAddress());
        } catch (IOException ex) {
            gameClient.displayError(GameVariables.BUNDLE.getString("MESSAGE_UNABLE_TO_CONNECT"));
            gameClient.close(true);
        }
    }//GEN-LAST:event_jButtonReappearActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        dispose();
        awt.close(true);
    }//GEN-LAST:event_jButtonExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonReappear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
